---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}-svc"
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: "{{ .Release.Name }}-svc"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-svc"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.server.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.server.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/component: "{{ .Release.Name }}-server"
  ports:
    {{ if .Values.server.service.healthz.enabled }}
    - name: {{ .Values.server.service.healthz.name }}
      port: {{ .Values.server.service.healthz.port }}
      protocol: {{ .Values.server.service.healthz.protocol }}
      targetPort: {{ .Values.server.service.healthz.targetPort }}
    {{ end }}
    {{- with .Values.server.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  type: {{ .Values.server.service.type }}