[Overrides]
; ModsFolderPath defaults to ./Mods next to the server binary

[General]
EnableHotReloadSystem=false
EnableAutoReloadingLuaMods=false
UseCache=true
InvalidateCacheIfDLLDiffers=true
EnableDebugKeyBindings=false
SecondsToScanBeforeGivingUp=30
bUseUObjectArrayCache=false
DoEarlyScan=false

[EngineVersionOverride]
MajorVersion=5
MinorVersion=1
DebugBuild=false

[Debug]
DebugConsoleEnabled=false
SimpleConsoleEnabled=true
GuiConsoleEnabled=0
GuiConsoleVisible=0

[Threads]
SigScannerNumThreads=-1
SigScannerMultithreadingModuleSizeThreshold=104857600

[Hooks]
HookProcessInternal=true
HookProcessLocalScriptFunction=true
HookLoadMap=true
HookInitGameState=true
HookCallFunctionByNameWithArguments=true
HookBeginPlay=true
HookEndPlay=true
